# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnRxSwift
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa'
  pod 'RxOptional'

end
