# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApp01
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'TestApp01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestApp01UITests' do
    # Pods for testing
  end

end
